### ISSUE TITLE
1画面上で画面遷移を実装する

### ISSUE THREAD

**Issue by gouf** [msm0046/timer_app#1]
# 背景

現状の [コミット (index.html)](https://github.com/msm0046/timer_app/blob/9b5a0b0c5dd00c813ebcbaec5538ad7e14d5279a/index.html) では つぎの、擬似的な 3画面が (途中だが) 実装されている

* `js-startScreen`
* `js-countdownScreen`
* `js-finishScreen`

# 課題・ゴール

JavaScript の制御によって、これら 3画面を、1画面ずつ表示できるようにする

実装途中の [コミット (index.js)](https://github.com/msm0046/timer_app/blob/9b5a0b0c5dd00c813ebcbaec5538ad7e14d5279a/index.js) がヒントとなる

# Pull Request について

実装単位は細かくていい。むしろ「1機能だけ実装しました」くらいの細かさがいい

→ 1 issue : n Pull Requests の関係性でぜんぜん OK

# その他

実装上で詰まったこと、知りたいことがあれば 別途、この issue を参照... #1 ...のような形式で指定しつつ... 質問のための issue を立てること

※「[自動リンクされた参照と URL - GitHub Docs](https://docs.github.com/ja/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests)」の「ショートリンク」を参照のこと

# Next Action(s)

画面表示の切り替えが実装できれば、あとは 3画面 個々の機能の実装に移る

**Comment by gouf** [comment]
@msm0046 実装方針、設計、ゴールへの道のりが見えないなどあれば、別 issue で質問してください！

細かな1機能でいいので、ブランチを切って Pull Request を作成してみてください

[pull request の作成 - GitHub Docs](https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

**Comment by gouf** [comment]
おー、質問と回答については GitHub に相当する機能があるので そちらのほうがいいかもしれませんね！

- [GitHub Discussions のドキュメント - GitHub Docs](https://docs.github.com/ja/discussions)

**Comment by gouf** [comment]
f914271 で実装済み。

**Comment by gouf** [comment]
@msm0046 次のステップを issue として設定してみてください。なるべく1歩だけ、「スモールステップ」で行きましょう。

**Comment by msm0046** [comment]
@gouf 
かしこまりました！考えてみます！

ありがとうございます🙇‍♀️
＞なるべく1歩だけ、「スモールステップ」で行きましょう。
